### ISSUE TITLE
train prototext file

### ISSUE THREAD

**Issue by AlexTS1980** [scott89/FCNT#3]
Which prototxt file did you use for training? In feature_net.prototxt I can't find a reference to the dataset and output layer.

**Comment by scott89** [comment]
We do not perform offline training. Both GNet and SNet are randomly initialized and trained online using solver/gnet_solver_xxx.prototxt and solver/snet_solver_xxx.prototxt, respectively, where xxx denotes the number of selected feature maps.

Thanks
