### ISSUE TITLE
caffe install

### ISSUE THREAD

**Issue by hanyamin** [scott89/FCNT#5]
When I install caffe you provided, I got some troubles. when I executed the order "make runtest" . I got some errors as follows
F0401 04:20:30.789280 147288 conv_layer.cpp:54] Check failed: group_ == 1 (3 vs. 1) 

The environments is as follows:
OS: Centos 7.0 64bit
cuda 7.5
cudnn4.0

Thanks

**Comment by scott89** [comment]
Hi! It seems that the error is encountered when running the code rather than compiling it. For convolutional layers, my implementation currently only supports conv group of 1.
Thanks
