### ISSUE TITLE
cudnn version

### ISSUE THREAD

**Issue by haoliyoupai09** [scott89/FCNT#6]
Could you tell me the version of your cudnn? When I compile your caffe-fcnt, i meet the following questions:
./include/caffe/util/cudnn.hpp(59): error: identifier "cudnnTensor4dDescriptor_t" is undefined
./include/caffe/util/cudnn.hpp(64): error: identifier "cudnnTensor4dDescriptor_t" is undefined
./include/caffe/util/cudnn.hpp(72): error: identifier "cudnnTensor4dDescriptor_t" is undefined
./include/caffe/util/cudnn.hpp(97): error: identifier "cudnnTensor4dDescriptor_t" is undefined
4 errors detected in the compilation of "/tmp/tmpxft_00004ef8_00000000-16_math_functions.compute_50.cpp1.ii".
make: *** [.build_release/src/caffe/util/math_functions.cuo] error 1

I think this is caused by the dismatch of cudnn version, but I tried to use cudnn 2.0, 3.0, 4.0, 5.0. All of these do not work, my cuda version is 7.5. Any help is appreciated and looking forward to your early reply.

**Comment by scott89** [comment]
FCNT does not adopt cudnn since there are some customized layers. Simply comment the USE_CUDNN flag in Makefile.config file may address this issue.
